server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.71.195.153:3306/student_management?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: wch924
mybatis-plus:
  global-config:
    db-config:
      id-type: auto